CREATE DATABASE POKEDEX
GO

USE POKEDEX
GO

CREATE TABLE CATEGORY
(
	CategoryId UNIQUEIDENTIFIER PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL
)
GO

CREATE TABLE POKEMON
(
	PokemonId UNIQUEIDENTIFIER PRIMARY KEY,
	Gender INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	CategoryId UNIQUEIDENTIFIER REFERENCES CATEGORY(CategoryId) NOT NULL,
	Hp INT NOT NULL,
	Attack INT NOT NULL,
	Defense INT NOT NULL,
	Speed INT NOT NULL,
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL
)
GO